/* Generated by npm run build:content. Edit content/*.js, then rebuild. */
(() => {
  // extension/shared/bridge.js
  async function call(type, payload = {}) {
    if (typeof globalThis.__LP_BRIDGE === "function") {
      return globalThis.__LP_BRIDGE(type, payload);
    }
    const response = await chrome.runtime.sendMessage({ type, payload });
    if (response && response.ok === false) {
      throw new Error(response.error || "LivePage request failed");
    }
    return response?.data;
  }
  function onBroadcast(handler) {
    if (typeof globalThis.__LP_ON_BROADCAST === "function") {
      return globalThis.__LP_ON_BROADCAST(handler);
    }
    const listener = (message) => {
      if (message?.broadcast) handler(message);
    };
    chrome.runtime.onMessage.addListener(listener);
    return () => chrome.runtime.onMessage.removeListener(listener);
  }

  // extension/shared/id.js
  function blockIdFromText(text) {
    const normalized = String(text || "").replace(/\s+/g, " ").trim().toLowerCase();
    let h = 2166136261;
    for (let i = 0; i < normalized.length; i += 1) {
      h ^= normalized.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return `b_${(h >>> 0).toString(16).padStart(8, "0")}`;
  }

  // extension/parse/page-parser.js
  var STRIP_SELECTORS = [
    "script",
    "style",
    "noscript",
    "svg",
    "canvas",
    "iframe",
    "nav",
    "footer",
    "header",
    "form",
    "aside",
    "[role='navigation']",
    "[role='banner']",
    "[role='contentinfo']",
    "[role='complementary']",
    "[aria-hidden='true']"
  ].join(",");
  var CONTENT_SELECTORS = [
    "article",
    "main",
    "[role='main']",
    ".post-content",
    ".entry-content",
    ".article-body",
    "#content",
    ".markdown-body"
  ];
  function parseDocument(doc, url = "") {
    const source = doc.cloneNode(true);
    source.querySelectorAll(STRIP_SELECTORS).forEach((el) => el.remove());
    const root = pickRoot(source) || source.body || source.documentElement;
    const blocks = [];
    const headings = [];
    const seen = /* @__PURE__ */ new Set();
    const walker = source.createTreeWalker(root, NodeFilter.SHOW_ELEMENT, {
      acceptNode(node2) {
        const tag = node2.tagName.toLowerCase();
        if (!["p", "li", "h1", "h2", "h3", "h4", "blockquote", "pre", "td"].includes(tag)) {
          return NodeFilter.FILTER_SKIP;
        }
        const text = normalizeText(node2.textContent);
        if (text.length < 24 && !/^h[1-4]$/.test(tag)) return NodeFilter.FILTER_SKIP;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    let node = walker.nextNode();
    while (node) {
      const text = normalizeText(node.textContent);
      const id = blockIdFromText(text);
      if (!seen.has(id)) {
        seen.add(id);
        const tag = node.tagName.toLowerCase();
        blocks.push({
          id,
          tag,
          text,
          heading: /^h[1-4]$/.test(tag)
        });
        if (/^h[1-4]$/.test(tag)) headings.push(text);
      }
      node = walker.nextNode();
    }
    const excerpt = blocks.filter((b) => !b.heading).slice(0, 3).map((b) => b.text).join(" ").slice(0, 420);
    const allText = blocks.map((b) => b.text).join(" ");
    const wordCount = allText ? allText.split(/\s+/).length : 0;
    return {
      url,
      title: (doc.querySelector("title")?.textContent || "").trim(),
      excerpt,
      headings,
      wordCount,
      contentHash: blockIdFromText(allText),
      blocks
    };
  }
  function pickRoot(doc) {
    for (const selector of CONTENT_SELECTORS) {
      const el = doc.querySelector(selector);
      if (el && normalizeText(el.textContent).length > 200) return el;
    }
    return doc.body;
  }
  function normalizeText(value) {
    return String(value || "").replace(/\s+/g, " ").trim();
  }

  // extension/parse/infinite-scroll.js
  var KNOWN_HOSTS = [
    "x.com",
    "twitter.com",
    "reddit.com",
    "old.reddit.com",
    "linkedin.com",
    "facebook.com",
    "instagram.com",
    "tiktok.com",
    "youtube.com",
    "news.ycombinator.com"
  ];
  var HINT_SELECTORS = [
    "[role='feed']",
    "[data-testid='infinite-scroll']",
    ".infinite-scroll",
    ".infinite-scroller",
    "[data-infinite]",
    "infinite-scroll"
  ];
  function hostLooksInfinite(url) {
    let host = "";
    try {
      host = new URL(url).hostname.replace(/^www\./i, "");
    } catch {
      return false;
    }
    return KNOWN_HOSTS.some((known) => host === known || host.endsWith(`.${known}`));
  }
  function domLooksInfinite(doc = document) {
    return HINT_SELECTORS.some((selector) => doc.querySelector(selector));
  }
  function createInfiniteScrollDetector(options = {}) {
    const threshold = options.threshold ?? 0.4;
    const minGrowths = options.minGrowths ?? 2;
    let lastHeight = measureHeight();
    let growths = 0;
    let flagged = Boolean(options.initial);
    const listeners = /* @__PURE__ */ new Set();
    function measureHeight() {
      const el = options.root || globalThis.document?.documentElement;
      return el ? el.scrollHeight : 0;
    }
    function check() {
      if (flagged) return flagged;
      const height = measureHeight();
      if (lastHeight > 400 && height > lastHeight * (1 + threshold)) {
        growths += 1;
        lastHeight = height;
        if (growths >= minGrowths) {
          flagged = true;
          listeners.forEach((fn) => fn(true));
        }
      } else if (height > lastHeight) {
        lastHeight = height;
      }
      return flagged;
    }
    function start() {
      if (typeof MutationObserver === "undefined") return () => {
      };
      const observer = new MutationObserver(() => {
        check();
      });
      observer.observe(options.root || document.body, {
        childList: true,
        subtree: true
      });
      const onScroll = () => check();
      (options.scrollTarget || window).addEventListener("scroll", onScroll, { passive: true });
      return () => {
        observer.disconnect();
        (options.scrollTarget || window).removeEventListener("scroll", onScroll);
      };
    }
    return {
      start,
      check,
      isFlagged: () => flagged,
      onFlag(fn) {
        listeners.add(fn);
        return () => listeners.delete(fn);
      }
    };
  }
  function evaluateInfiniteScroll(url, doc, extras = {}) {
    if (hostLooksInfinite(url)) {
      return { infinite: true, reason: "This looks like a feed that keeps growing." };
    }
    if (domLooksInfinite(doc)) {
      return { infinite: true, reason: "This page is an infinite feed." };
    }
    if (extras.heuristic) {
      return { infinite: true, reason: "This page grew while you were reading." };
    }
    return { infinite: false, reason: null };
  }

  // extension/parse/quote.js
  var SKIP = "script,style,noscript,textarea,input,lp-root,.lp-ignore";
  function quoteFromRange(range, root = document.body) {
    if (!range || range.collapsed) return null;
    const map = flattenText(root);
    const start = flatOffsetFromPoint(map, range.startContainer, range.startOffset, "start");
    const end = flatOffsetFromPoint(map, range.endContainer, range.endOffset, "end");
    let exact = "";
    if (start != null && end != null && end > start) {
      exact = map.text.slice(start, end).trim();
    }
    if (!exact) exact = normalizeText(range.toString());
    if (!exact) return null;
    const index = start != null && end > start ? start : map.text.indexOf(exact);
    const before = index >= 0 ? map.text.slice(Math.max(0, index - 48), index) : textBefore(range, root, 48);
    const after = index >= 0 ? map.text.slice(index + exact.length, index + exact.length + 48) : textAfter(range, root, 48);
    return {
      exact,
      prefix: before.slice(-32),
      suffix: after.slice(0, 32)
    };
  }
  function locateQuote(hay, selector) {
    const exact = normalizeText(selector?.exact || "");
    if (!exact || !hay) return null;
    const prefix = normalizeText(selector.prefix || "");
    const suffix = normalizeText(selector.suffix || "");
    const hits = [];
    let from = 0;
    while (from <= hay.length) {
      const index = hay.indexOf(exact, from);
      if (index === -1) break;
      hits.push(index);
      from = index + 1;
    }
    if (hits.length) return pickBest(hay, hits, exact.length, prefix, suffix);
    for (let trim = 1; trim <= Math.min(4, Math.floor(exact.length / 5)); trim += 1) {
      const inner = exact.slice(trim, exact.length - trim);
      if (inner.length < 8) break;
      const index = hay.indexOf(inner);
      if (index >= 0) {
        return pickBest(hay, [index], inner.length, prefix, suffix);
      }
    }
    if (prefix.length >= 8 && suffix.length >= 8) {
      const p = hay.indexOf(prefix);
      if (p >= 0) {
        const s = hay.indexOf(suffix, p + prefix.length);
        if (s > p) return { start: p + prefix.length, end: s };
      }
    }
    if (exact.length >= 12 && exact.length <= 240) {
      return fuzzyWindow(hay, exact, prefix, suffix);
    }
    return null;
  }
  function findQuote(root, selector) {
    if (!selector?.exact) return null;
    const map = flattenText(root);
    const found = locateQuote(map.text, selector);
    if (!found) return null;
    return rangeFromOffsets(map, found.start, found.end);
  }
  function wrapRange(range, highlight) {
    if (!range || range.collapsed) return [];
    const marks = [];
    const points = splitBoundaries(range);
    const ancestor = range.commonAncestorContainer.nodeType === Node.ELEMENT_NODE ? range.commonAncestorContainer : range.commonAncestorContainer.parentElement;
    if (!ancestor) return [];
    const walker = document.createTreeWalker(ancestor, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        if (!node.textContent) return NodeFilter.FILTER_REJECT;
        if (node.parentElement?.closest(SKIP)) return NodeFilter.FILTER_REJECT;
        if (node.parentElement?.closest("mark.lp-hl")) return NodeFilter.FILTER_REJECT;
        if (!rangeIntersectsNode(range, node)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    const nodes = [];
    let current = walker.nextNode();
    while (current) {
      nodes.push(current);
      current = walker.nextNode();
    }
    for (const textNode of nodes) {
      let start = 0;
      let end = textNode.textContent.length;
      if (textNode === points.start.node) start = points.start.offset;
      if (textNode === points.end.node) end = points.end.offset;
      if (start >= end) continue;
      const middle = splitTextRange(textNode, start, end);
      const mark = document.createElement("mark");
      mark.className = "lp-hl";
      mark.dataset.lpId = highlight.id;
      mark.dataset.lpColor = highlight.color;
      mark.dataset.lpThread = highlight.threadId || "";
      middle.parentNode.insertBefore(mark, middle);
      mark.appendChild(middle);
      marks.push(mark);
    }
    return marks;
  }
  function unwrapHighlight(root, highlightId) {
    root.querySelectorAll(`mark.lp-hl[data-lp-id="${cssEscape(highlightId)}"]`).forEach((mark) => {
      const parent = mark.parentNode;
      while (mark.firstChild) parent.insertBefore(mark.firstChild, mark);
      parent.removeChild(mark);
      parent.normalize();
    });
  }
  function flattenText(root) {
    const spans = [];
    let rawCombined = "";
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(node2) {
        if (!node2.textContent) return NodeFilter.FILTER_REJECT;
        if (node2.parentElement?.closest(SKIP)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    let node = walker.nextNode();
    while (node) {
      const raw = node.textContent;
      spans.push({ node, rawStart: rawCombined.length, rawEnd: rawCombined.length + raw.length });
      rawCombined += raw;
      node = walker.nextNode();
    }
    const { text, rawAtFlat } = collapseMap(rawCombined);
    return { spans, text, rawAtFlat };
  }
  function collapseMap(raw) {
    const textChars = [];
    const rawAtFlat = [];
    let pendingSpace = false;
    let sawContent = false;
    for (let i = 0; i < raw.length; i += 1) {
      if (/\s/.test(raw[i])) {
        if (sawContent) pendingSpace = true;
        continue;
      }
      if (pendingSpace) {
        textChars.push(" ");
        rawAtFlat.push(i);
        pendingSpace = false;
      }
      textChars.push(raw[i]);
      rawAtFlat.push(i);
      sawContent = true;
    }
    return { text: textChars.join(""), rawAtFlat };
  }
  function flatOffsetFromPoint(map, container, offset, edge) {
    const point = resolveToText(container, offset, edge);
    if (!point) return edge === "end" ? map.text.length : 0;
    const span = map.spans.find((s) => s.node === point.node);
    if (!span) return null;
    const raw = span.rawStart + clamp(point.offset, 0, point.node.textContent.length);
    if (!map.rawAtFlat.length) return 0;
    if (edge === "end") {
      let last = 0;
      for (let i = 0; i < map.rawAtFlat.length; i += 1) {
        if (map.rawAtFlat[i] < raw) last = i + 1;
        else break;
      }
      return last;
    }
    for (let i = 0; i < map.rawAtFlat.length; i += 1) {
      if (map.rawAtFlat[i] >= raw) return i;
    }
    return map.text.length;
  }
  function rangeFromOffsets(map, start, end) {
    const range = document.createRange();
    const startPoint = pointFromFlat(map, start, "start");
    const endPoint = pointFromFlat(map, Math.max(start, end), "end");
    if (!startPoint || !endPoint) return null;
    try {
      range.setStart(startPoint.node, startPoint.offset);
      range.setEnd(endPoint.node, endPoint.offset);
    } catch {
      return null;
    }
    return range.collapsed ? null : range;
  }
  function pointFromFlat(map, flatIndex, edge) {
    if (!map.spans.length) return null;
    const idx = clamp(flatIndex, 0, Math.max(0, map.rawAtFlat.length - (edge === "end" ? 0 : 1)));
    const raw = edge === "end" && flatIndex >= map.rawAtFlat.length ? map.spans[map.spans.length - 1].rawEnd : map.rawAtFlat[Math.min(idx, map.rawAtFlat.length - 1)];
    const target = edge === "end" ? raw : raw;
    const span = map.spans.find((s) => target >= s.rawStart && target < s.rawEnd) || (edge === "end" ? map.spans[map.spans.length - 1] : map.spans[0]);
    return { node: span.node, offset: clamp(target - span.rawStart, 0, span.node.textContent.length) };
  }
  function resolveToText(container, offset, edge) {
    if (!container) return null;
    if (container.nodeType === Node.TEXT_NODE) {
      return { node: container, offset };
    }
    const kids = container.childNodes;
    if (edge === "end") {
      if (offset <= 0) return firstTextPoint(container);
      const child2 = kids[Math.min(offset, kids.length) - 1];
      return lastTextPoint(child2 || container);
    }
    if (offset >= kids.length) return lastTextPoint(container);
    const child = kids[offset];
    return child ? firstTextPoint(child) : firstTextPoint(container);
  }
  function pickBest(hay, hits, length, prefix, suffix) {
    let best = hits[0];
    let bestScore = -1;
    for (const index of hits) {
      const pre = hay.slice(Math.max(0, index - 32), index);
      const suf = hay.slice(index + length, index + length + 32);
      let score = 0;
      if (prefix && pre.endsWith(prefix)) score += 3;
      else if (prefix && pre.includes(prefix.slice(-12))) score += 1;
      if (suffix && suf.startsWith(suffix)) score += 3;
      else if (suffix && suf.includes(suffix.slice(0, 12))) score += 1;
      if (score > bestScore) {
        bestScore = score;
        best = index;
      }
    }
    return { start: best, end: best + length };
  }
  function fuzzyWindow(hay, exact, prefix, suffix) {
    const maxDist = Math.max(2, Math.floor(exact.length * 0.1));
    let best = null;
    let bestScore = maxDist + 1;
    const step = exact.length > 80 ? 3 : 1;
    for (let i = 0; i <= hay.length - exact.length; i += step) {
      const slice = hay.slice(i, i + exact.length);
      const dist = levenshtein(slice, exact, maxDist);
      if (dist > maxDist) continue;
      let score = dist;
      if (prefix && hay.slice(Math.max(0, i - 32), i).endsWith(prefix)) score -= 0.5;
      if (suffix && hay.slice(i + exact.length, i + exact.length + 32).startsWith(suffix)) score -= 0.5;
      if (score < bestScore) {
        bestScore = score;
        best = { start: i, end: i + exact.length };
      }
    }
    return best;
  }
  function levenshtein(a, b, max) {
    if (a === b) return 0;
    const m = a.length;
    const n = b.length;
    if (Math.abs(m - n) > max) return max + 1;
    let prev = new Array(n + 1);
    let next = new Array(n + 1);
    for (let j = 0; j <= n; j += 1) prev[j] = j;
    for (let i = 1; i <= m; i += 1) {
      next[0] = i;
      let rowMin = next[0];
      for (let j = 1; j <= n; j += 1) {
        const cost = a[i - 1] === b[j - 1] ? 0 : 1;
        next[j] = Math.min(prev[j] + 1, next[j - 1] + 1, prev[j - 1] + cost);
        if (next[j] < rowMin) rowMin = next[j];
      }
      if (rowMin > max) return max + 1;
      [prev, next] = [next, prev];
    }
    return prev[n];
  }
  function splitBoundaries(range) {
    const start = resolveToText(range.startContainer, range.startOffset, "start") || {
      node: range.startContainer,
      offset: range.startOffset
    };
    const end = resolveToText(range.endContainer, range.endOffset, "end") || {
      node: range.endContainer,
      offset: range.endOffset
    };
    return { start, end };
  }
  function splitTextRange(textNode, start, end) {
    let node = textNode;
    if (end < node.textContent.length) node.splitText(end);
    if (start > 0) node = node.splitText(start);
    return node;
  }
  function rangeIntersectsNode(range, node) {
    const probe = document.createRange();
    probe.selectNodeContents(node);
    return range.compareBoundaryPoints(Range.END_TO_START, probe) < 0 && range.compareBoundaryPoints(Range.START_TO_END, probe) > 0;
  }
  function firstTextPoint(node) {
    if (!node) return null;
    if (node.nodeType === Node.TEXT_NODE) return { node, offset: 0 };
    const walker = document.createTreeWalker(node, NodeFilter.SHOW_TEXT);
    const found = walker.nextNode();
    return found ? { node: found, offset: 0 } : null;
  }
  function lastTextPoint(node) {
    if (!node) return null;
    if (node.nodeType === Node.TEXT_NODE) return { node, offset: node.textContent.length };
    const walker = document.createTreeWalker(node, NodeFilter.SHOW_TEXT);
    let last = null;
    let current = walker.nextNode();
    while (current) {
      last = current;
      current = walker.nextNode();
    }
    return last ? { node: last, offset: last.textContent.length } : null;
  }
  function textBefore(range, root, limit) {
    const pre = document.createRange();
    pre.selectNodeContents(root);
    pre.setEnd(range.startContainer, range.startOffset);
    return normalizeText(pre.toString()).slice(-limit);
  }
  function textAfter(range, root, limit) {
    const post = document.createRange();
    post.selectNodeContents(root);
    post.setStart(range.endContainer, range.endOffset);
    return normalizeText(post.toString()).slice(0, limit);
  }
  function clamp(n, min, max) {
    return Math.min(max, Math.max(min, n));
  }
  function cssEscape(value) {
    if (typeof CSS !== "undefined" && CSS.escape) return CSS.escape(value);
    return String(value).replace(/"/g, '\\"');
  }

  // extension/content/highlights.js
  function restoreHighlights(root, highlights) {
    const restored = [];
    for (const highlight of highlights || []) {
      unwrapHighlight(root, highlight.id);
      const range = findQuote(root, {
        exact: highlight.text,
        prefix: highlight.prefix,
        suffix: highlight.suffix
      });
      if (!range) continue;
      wrapRange(range, highlight);
      restored.push(highlight.id);
    }
    return restored;
  }
  function applyRangeHighlight(range, highlight, root = document.body) {
    if (!range || range.collapsed) return [];
    const quote = quoteFromRange(range, root);
    if (!quote) return [];
    Object.assign(highlight, {
      text: quote.exact,
      prefix: quote.prefix,
      suffix: quote.suffix
    });
    unwrapHighlight(root, highlight.id);
    const located = findQuote(root, quote) || range;
    return wrapRange(located, highlight);
  }
  function marksFor(highlightId) {
    return [...document.querySelectorAll(`mark.lp-hl[data-lp-id="${CSS.escape(highlightId)}"]`)];
  }
  function recolorMarks(highlightId, color) {
    marksFor(highlightId).forEach((mark) => {
      mark.dataset.lpColor = color;
    });
  }
  function highlightRect(highlightId) {
    const marks = marksFor(highlightId);
    if (!marks.length) return null;
    const rects = marks.map((m) => m.getBoundingClientRect());
    return {
      top: Math.min(...rects.map((r) => r.top)),
      bottom: Math.max(...rects.map((r) => r.bottom)),
      left: Math.min(...rects.map((r) => r.left)),
      right: Math.max(...rects.map((r) => r.right)),
      height: Math.max(...rects.map((r) => r.bottom)) - Math.min(...rects.map((r) => r.top))
    };
  }
  function selectionIsSafe(selection, snapshotBlockTexts) {
    if (!selection || selection.isCollapsed) return false;
    const text = selection.toString().trim();
    if (text.length < 2) return false;
    if (!snapshotBlockTexts) return true;
    const hay = snapshotBlockTexts.join("\n");
    return hay.includes(text.slice(0, Math.min(80, text.length)));
  }

  // extension/shared/colors.js
  var COLORS = {
    lemon: { id: "lemon", name: "Lemon", fill: "#F6E27A", ink: "#5C4A10" },
    moss: { id: "moss", name: "Moss", fill: "#A8D5A2", ink: "#1F3D28" },
    sky: { id: "sky", name: "Sky", fill: "#A8D4F0", ink: "#1A3A52" },
    rose: { id: "rose", name: "Rose", fill: "#F3B6C4", ink: "#5C2436" },
    iris: { id: "iris", name: "Iris", fill: "#C9B7F2", ink: "#3A2A5C" },
    sand: { id: "sand", name: "Sand", fill: "#E7C899", ink: "#4A3518" }
  };
  var COLOR_IDS = Object.keys(COLORS);

  // extension/shared/time.js
  function formatRelative(ts, from = Date.now()) {
    if (!ts) return "never";
    const delta = Math.max(0, from - ts);
    const minute = 60 * 1e3;
    const hour = 60 * minute;
    const day = 24 * hour;
    if (delta < minute) return "just now";
    if (delta < hour) return `${Math.floor(delta / minute)}m ago`;
    if (delta < day) return `${Math.floor(delta / hour)}h ago`;
    if (delta < 14 * day) return `${Math.floor(delta / day)}d ago`;
    return new Date(ts).toLocaleDateString(void 0, {
      month: "short",
      day: "numeric"
    });
  }

  // extension/content/overlay.js
  var import_meta = {};
  var GUTTER = 328;
  var CARD_GAP = 10;
  var FALLBACK_CSS = `
:host { all: initial; display: block; pointer-events: none; z-index: 2147483000; }
:host([data-lp="root"]) {
  position: absolute; top: 0; right: 0;
  width: var(--lp-gutter, 328px); min-height: 100%; height: var(--lp-doc-height, 100%);
}
:host([data-lp="float"]) {
  position: fixed; inset: 0; width: 100%; height: 100%; overflow: visible;
  z-index: 2147483640; pointer-events: none;
}
.lp-root, .lp-float { font-family: ui-sans-serif, "Segoe UI", system-ui, sans-serif; color: #1c1712; font-size: 13px; }
.banner, .feed-offer, .toolbar, .toast, .card { pointer-events: auto; }
.banner[hidden], .feed-offer[hidden], .toolbar[hidden], .toast[hidden] { display: none !important; }
.toolbar {
  position: fixed; z-index: 2147483646; display: flex; gap: 4px; align-items: center;
  padding: 6px; background: #fffcf7; border: 1px solid rgba(28,23,18,0.12);
  border-radius: 999px; box-shadow: 0 14px 40px rgba(28,23,18,0.16);
}
.swatch { width: 18px; height: 18px; border-radius: 50%; border: 1px solid rgba(28,23,18,0.18); cursor: pointer; background: var(--lp-mark); }
button.ghost { appearance: none; border: 0; background: transparent; color: #1c1712; padding: 6px 9px; font: inherit; cursor: pointer; border-radius: 999px; }
.banner, .toast, .feed-offer {
  position: fixed; z-index: 2147483646; background: #fffcf7; border: 1px solid rgba(28,23,18,0.1);
  border-radius: 14px; padding: 10px 12px; box-shadow: 0 10px 40px rgba(28,23,18,0.12);
}
.banner { top: 12px; left: 50%; transform: translateX(-50%); display: flex; gap: 10px; align-items: center; }
.toast { bottom: 20px; left: 50%; transform: translateX(-50%); background: #1c1712; color: #f6f1e8; border-radius: 999px; }
button.solid { appearance: none; border: 0; background: #3f6b52; color: #f6f1e8; padding: 6px 10px; font: inherit; cursor: pointer; border-radius: 999px; font-weight: 600; }
`;
  function makeHost(kind) {
    const host = document.createElement("div");
    host.className = "lp-ignore";
    host.setAttribute("data-lp", kind);
    return host;
  }
  var Overlay = class {
    constructor() {
      this.host = makeHost("root");
      this.shadow = this.host.attachShadow({ mode: "open" });
      this.floatHost = makeHost("float");
      this.floatShadow = this.floatHost.attachShadow({ mode: "open" });
      this.page = null;
      this.activeThreadId = null;
      this.locked = false;
      this.snapshotTexts = null;
      this.handlers = {};
      this.sendMode = "comment";
      this.threadModes = {};
      this.awaitingAgent = null;
      this.els = { toolbar: null, banner: null, toast: null, feedOffer: null, gutter: null };
      this.mountFloat();
      this.bind();
      this.ready = this.render();
    }
    mountFloat() {
      this.floatHost.style.cssText = "all:initial;position:fixed;inset:0;width:100%;height:100%;overflow:visible;pointer-events:none;z-index:2147483646;";
      this.floatShadow.innerHTML = `
      <style>${FALLBACK_CSS}</style>
      <div class="lp-float">
        <div class="toolbar" hidden></div>
        <div class="banner" hidden></div>
        <div class="toast" hidden></div>
        <div class="feed-offer" hidden></div>
      </div>
    `;
      this.els.toolbar = this.floatShadow.querySelector(".toolbar");
      this.els.banner = this.floatShadow.querySelector(".banner");
      this.els.toast = this.floatShadow.querySelector(".toast");
      this.els.feedOffer = this.floatShadow.querySelector(".feed-offer");
      this.attachHosts();
    }
    attachHosts() {
      const root = document.documentElement;
      if (!root) return;
      if (this.floatHost.parentNode !== root) root.appendChild(this.floatHost);
      if (this.els?.gutter && this.host.parentNode !== root) root.appendChild(this.host);
    }
    async render() {
      let css = "";
      try {
        const cssUrl = chrome.runtime?.getURL ? chrome.runtime.getURL("content/overlay.css") : new URL("./overlay.css", import_meta.url).href;
        css = await Promise.race([
          fetch(cssUrl).then((r) => r.text()),
          new Promise((resolve) => setTimeout(() => resolve(""), 800))
        ]);
      } catch {
        css = "";
      }
      const style = `<style>${FALLBACK_CSS}
${css}</style>`;
      this.shadow.innerHTML = `
      ${style}
      <div class="lp-root">
        <div class="gutter"></div>
      </div>
    `;
      this.els.gutter = this.shadow.querySelector(".gutter");
      if (css && this.floatShadow.querySelector("style")) {
        this.floatShadow.querySelector("style").textContent = `${FALLBACK_CSS}
${css}`;
      }
      document.documentElement.style.setProperty("--lp-gutter", `${GUTTER}px`);
      if (!document.getElementById("lp-gutter-style")) {
        const rail = document.createElement("style");
        rail.id = "lp-gutter-style";
        rail.textContent = `
        html.lp-rail-on {
          position: relative;
          box-sizing: border-box;
          padding-right: var(--lp-gutter, 328px) !important;
          scroll-padding-right: var(--lp-gutter, 328px);
        }
      `;
        document.documentElement.appendChild(rail);
      }
      document.documentElement.appendChild(this.host);
      this.attachHosts();
      this.applyRail();
    }
    bind() {
      window.addEventListener("resize", () => this.layoutCards(), { passive: true });
      document.addEventListener("keydown", (event) => {
        if (event.key !== "Escape") return;
        const menu = this.els?.gutter?.querySelector(".send-menu:not([hidden])");
        if (menu) {
          menu.hidden = true;
          return;
        }
        if (this.awaitingAgent) {
          this.awaitingAgent = null;
          this.renderCards();
          return;
        }
        this.closePanel();
      });
      document.addEventListener("mousedown", (event) => {
        if (!this.activeThreadId) return;
        if (event.target.closest?.("mark.lp-hl")) return;
        if (this.ownsEvent(event)) return;
        this.closePanel();
      });
    }
    ownsEvent(event) {
      const path = event.composedPath?.() || [];
      return path.includes(this.host) || path.includes(this.floatHost);
    }
    setPage(page2) {
      this.page = page2;
      if (this.awaitingAgent) {
        const thread = page2?.threads?.find((t) => t.id === this.awaitingAgent.threadId);
        const status = thread?.awaitingAgent?.status;
        if (status !== "pending" && status !== "error") this.awaitingAgent = null;
      }
      this.renderCards();
      this.applyRail();
      if (this.activeThreadId) this.openThread(this.activeThreadId);
    }
    applyRail() {
      const show = (this.page?.highlights || []).length > 0;
      this.host.hidden = !show;
      document.documentElement.classList.toggle("lp-rail-on", show);
      if (show) {
        document.documentElement.style.setProperty("--lp-gutter", `${GUTTER}px`);
      } else {
        document.documentElement.style.removeProperty("--lp-gutter");
      }
    }
    setLock({ locked, reason, snapshotTexts }) {
      this.locked = locked;
      this.snapshotTexts = snapshotTexts || null;
      if (!this.els?.banner) return;
      if (!locked) {
        this.els.banner.hidden = true;
        return;
      }
      this.els.banner.hidden = false;
      this.els.banner.innerHTML = `
      <p><strong>Infinite page.</strong> ${reason || "This page keeps growing."} Highlighting is locked until you snapshot the current view.</p>
      <button class="solid" data-act="snapshot">Snapshot</button>
      <button class="ghost" data-act="dismiss">Not now</button>
    `;
      this.els.banner.querySelector("[data-act='snapshot']").onclick = () => this.handlers.onSnapshot?.();
      this.els.banner.querySelector("[data-act='dismiss']").onclick = () => {
        this.els.banner.hidden = true;
      };
    }
    offerFeed(feed, { onAdd, onDismiss } = {}) {
      const el = this.els.feedOffer;
      if (!el) return;
      if (!feed) {
        el.hidden = true;
        el.innerHTML = "";
        return;
      }
      el.hidden = false;
      el.innerHTML = `
      <p><strong>RSS on this page.</strong> ${escapeHtml(feed.title || feed.url)}</p>
      <input type="text" data-act="tags" placeholder="tags: design, weekly" />
      <button class="solid" data-act="add">Add feed</button>
      <button class="ghost" data-act="dismiss">Not now</button>
    `;
      el.querySelector("[data-act='add']").onclick = () => {
        const tags = el.querySelector("[data-act='tags']")?.value || "";
        onAdd?.(tags);
      };
      el.querySelector("[data-act='dismiss']").onclick = () => {
        el.hidden = true;
        onDismiss?.();
      };
    }
    showToolbar(rect, { onHighlight, onComment, onSnapshot } = {}) {
      this.attachHosts();
      const bar = this.els?.toolbar;
      if (!bar) return;
      bar.hidden = false;
      bar.removeAttribute("hidden");
      if (onSnapshot && !onHighlight) {
        bar.innerHTML = `<button class="solid" data-act="snapshot">Snapshot to highlight</button>`;
      } else {
        bar.innerHTML = COLOR_IDS.map(
          (id) => `<button class="swatch" title="${COLORS[id].name}" style="--lp-mark:${COLORS[id].fill}" data-color="${id}"></button>`
        ).join("") + `<button class="ghost" data-act="comment">Comment</button>`;
      }
      const top = rect.top - 44;
      const left = Math.min(rect.left, document.documentElement.clientWidth - 280);
      bar.style.top = `${Math.max(8, top)}px`;
      bar.style.left = `${Math.max(8, left)}px`;
      bar.onpointerdown = (event) => event.preventDefault();
      bar.onmousedown = (event) => event.preventDefault();
      bar.querySelector("[data-act='snapshot']")?.addEventListener("click", (event) => {
        event.preventDefault();
        this.hideToolbar();
        onSnapshot?.();
      });
      bar.querySelectorAll(".swatch").forEach((btn) => {
        btn.onclick = (event) => {
          event.preventDefault();
          onHighlight?.(btn.dataset.color);
          this.hideToolbar();
        };
      });
      bar.querySelector("[data-act='comment']")?.addEventListener("click", (event) => {
        event.preventDefault();
        onComment?.();
        this.hideToolbar();
      });
    }
    hideToolbar() {
      if (this.els?.toolbar) this.els.toolbar.hidden = true;
    }
    toast(text) {
      if (!this.els?.toast) return;
      this.els.toast.hidden = false;
      this.els.toast.textContent = text;
      clearTimeout(this._toast);
      this._toast = setTimeout(() => {
        this.els.toast.hidden = true;
      }, 2400);
    }
    renderCards() {
      if (!this.page || !this.els?.gutter) return;
      this.els.gutter.innerHTML = this.page.highlights.map((highlight) => this.cardHtml(highlight)).join("");
      this.els.gutter.querySelectorAll(".card").forEach((card) => this.bindCard(card));
      this.layoutCards();
      this.markActiveHighlights();
      this.applyRail();
      const open = this.els.gutter.querySelector(".card.is-open .messages");
      if (open) open.scrollTop = open.scrollHeight;
    }
    cardHtml(highlight) {
      const thread = this.threadFor(highlight.id);
      const open = Boolean(thread && thread.id === this.activeThreadId);
      const color = COLORS[highlight.color]?.fill || "#F6E27A";
      const preview = thread?.messages?.[0]?.content || "Add a comment";
      const count = thread?.messages?.length || 0;
      if (!open) {
        return `
        <article class="card" data-highlight="${highlight.id}" data-thread="${thread?.id || ""}" style="--lp-mark:${color}">
          <p class="meta-line">
            <span>${escapeHtml(thread?.branchLabel || "note")}</span>
            <span>${count ? `${count}` : ""}</span>
            <button type="button" class="hl-delete" data-act="delete-hl" title="Delete highlight">\xD7</button>
          </p>
          <p class="quote">${escapeHtml(clip(highlight.text, 90))}</p>
          <p class="preview">${escapeHtml(clip(preview, 110))}</p>
        </article>`;
      }
      const branches = this.page.threads.filter((t) => t.highlightId === highlight.id);
      const mode = this.effectiveSendMode(thread);
      return `
      <article class="card is-open" data-highlight="${highlight.id}" data-thread="${thread.id}" style="--lp-mark:${color}">
        <button class="close" title="Collapse">\xD7</button>
        <div class="hl-toolbar">
          <div class="swatches">
            ${COLOR_IDS.map(
        (id) => `<button type="button" class="swatch ${highlight.color === id ? "is-on" : ""}" title="${COLORS[id].name}" style="--lp-mark:${COLORS[id].fill}" data-color="${id}"></button>`
      ).join("")}
          </div>
          <button type="button" class="ghost" data-act="move-hl">Replace span</button>
          <button type="button" class="hl-delete" data-act="delete-hl">Delete</button>
        </div>
        <p class="quote">${escapeHtml(clip(highlight.text, 180))}</p>
        ${branches.length > 1 ? `<div class="branch-list">${branches.map(
        (b) => `<button class="chip ${b.id === thread.id ? "is-on" : ""}" data-branch="${b.id}">${escapeHtml(
          b.parentId ? `\u21B3 ${b.branchLabel}` : b.branchLabel
        )}</button>`
      ).join("")}</div>` : ""}
        <div class="messages">
          ${this.messagesHtml(highlight, thread)}
        </div>
        <div class="composer">
          ${thread.awaitingAgent ? `<div class="packet">
                  <p class="kicker">${escapeHtml(awaitingCopy(thread.awaitingAgent))}</p>
                  ${thread.awaitingAgent.status === "error" ? `<p class="error">${escapeHtml(thread.awaitingAgent.error || "Agent host did not reply.")}</p>
                  <textarea class="packet-md" readonly>${escapeHtml(thread.awaitingAgent.packet || "")}</textarea>
                  <button type="button" class="ghost" data-act="copy-packet">Copy packet</button>` : `<p class="hint">LivePage is talking to ${escapeHtml(agentName(thread.awaitingAgent.agent))}${thread.awaitingAgent.model ? ` \xB7 ${escapeHtml(thread.awaitingAgent.model)}` : ""}. The reply will land in this thread.</p>`}
                </div>` : ""}
          <textarea placeholder="${escapeHtml(this.composerPlaceholder(thread))}"></textarea>
          <div class="send">
            <button type="button" class="solid send-main" data-act="send">${escapeHtml(this.sendLabel(thread))}</button>
            <button type="button" class="solid send-caret" data-act="menu" aria-label="Send options">\u25BE</button>
            <div class="send-menu" hidden>
              <button type="button" data-mode="comment" class="${mode === "comment" && !thread.awaitingAgent ? "is-on" : ""}">Comment</button>
              <button type="button" data-mode="cursor" class="${mode === "cursor" || thread.awaitingAgent?.agent === "cursor" ? "is-on" : ""}">Ask Cursor</button>
              <button type="button" data-mode="claude-code" class="${mode === "claude-code" || thread.awaitingAgent?.agent === "claude-code" ? "is-on" : ""}">Ask Claude Code</button>
            </div>
          </div>
        </div>
      </article>`;
    }
    messagesHtml(highlight, thread) {
      const siblings = (this.page?.threads || []).filter((t) => t.highlightId === highlight.id);
      const suggested = nextForkLabel(this.page, thread);
      return (thread.messages || []).map((m) => {
        const forks = siblings.filter((b) => b.id !== thread.id && b.forkedFromMessageId === m.id);
        return `
          <article class="msg ${m.role === "agent" ? "is-agent" : "is-you"}" data-msg="${m.id}">
            <div class="meta"><span>${escapeHtml(labelOf(m))}</span><span>${formatRelative(m.createdAt)}</span></div>
            <p>${escapeHtml(m.content)}</p>
            <div class="msg-actions">
              <button type="button" class="fork" data-fork="${m.id}">Branch</button>
              <button type="button" class="delete" data-delete="${m.id}">Delete</button>
            </div>
            <form class="fork-form" hidden data-fork-form="${m.id}">
              <input type="text" name="label" value="${escapeHtml(suggested)}" placeholder="Branch name" maxlength="48" />
              <button type="submit">Start branch</button>
              <button type="button" data-act="cancel-fork">Cancel</button>
            </form>
          </article>
          ${forks.length ? `<div class="fork-off">
                  <span class="fork-kicker">branched</span>
                  ${forks.map(
          (b) => `<button type="button" class="chip" data-branch="${b.id}">${escapeHtml(b.branchLabel)}</button>`
        ).join("")}
                </div>` : ""}`;
      }).join("");
    }
    bindCard(card) {
      const highlightId = card.dataset.highlight;
      const threadId = card.dataset.thread;
      card.onclick = (event) => {
        if (event.target.closest("button, textarea, select, a, .composer, .fork-form, input")) return;
        if (threadId) this.openThread(threadId);
        else this.handlers.onOpenHighlight?.(highlightId);
      };
      const close = card.querySelector(".close");
      if (close) close.onclick = (event) => {
        event.stopPropagation();
        this.closePanel();
      };
      card.querySelectorAll("[data-color]").forEach((btn) => {
        btn.onclick = (event) => {
          event.stopPropagation();
          this.handlers.onRecolorHighlight?.(highlightId, btn.dataset.color);
        };
      });
      card.querySelector("[data-act='move-hl']")?.addEventListener("click", (event) => {
        event.stopPropagation();
        this.handlers.onMoveHighlight?.(highlightId);
      });
      card.querySelectorAll("[data-act='delete-hl']").forEach((btn) => {
        btn.onclick = (event) => {
          event.stopPropagation();
          this.handlers.onDeleteHighlight?.(highlightId);
        };
      });
      card.querySelectorAll("[data-branch]").forEach((btn) => {
        btn.onclick = (event) => {
          event.stopPropagation();
          this.openThread(btn.dataset.branch);
        };
      });
      card.querySelectorAll("[data-fork]").forEach((btn) => {
        btn.onclick = (event) => {
          event.stopPropagation();
          card.querySelectorAll(".fork-form").forEach((form2) => {
            form2.hidden = form2.dataset.forkForm !== btn.dataset.fork;
          });
          const form = card.querySelector(`[data-fork-form="${CSS.escape(btn.dataset.fork)}"]`);
          const input = form?.querySelector("input");
          if (input) {
            input.focus();
            input.select();
          }
        };
      });
      card.querySelectorAll(".fork-form").forEach((form) => {
        form.onsubmit = (event) => {
          event.preventDefault();
          event.stopPropagation();
          const label = form.querySelector("input")?.value.trim() || "branch";
          this.handlers.onFork?.(threadId, form.dataset.forkForm, label);
        };
      });
      card.querySelectorAll("[data-act='cancel-fork']").forEach((btn) => {
        btn.onclick = (event) => {
          event.stopPropagation();
          btn.closest(".fork-form").hidden = true;
        };
      });
      card.querySelectorAll("[data-delete]").forEach((btn) => {
        btn.onclick = (event) => {
          event.stopPropagation();
          this.handlers.onDeleteMessage?.(threadId, btn.dataset.delete);
        };
      });
      const textarea = card.querySelector("textarea:not(.packet-md)");
      const menu = card.querySelector(".send-menu");
      const sendBtn = card.querySelector("[data-act='send']");
      const caret = card.querySelector("[data-act='menu']");
      const copyPacket = card.querySelector("[data-act='copy-packet']");
      const packetField = card.querySelector(".packet-md");
      const thread = this.page?.threads.find((t) => t.id === threadId);
      if (copyPacket && packetField) {
        copyPacket.onclick = async (event) => {
          event.stopPropagation();
          try {
            await navigator.clipboard.writeText(packetField.value);
            this.toast("Packet copied. Paste it into the agent, then paste the reply here.");
          } catch {
            packetField.focus();
            packetField.select();
            this.toast("Select the packet and copy it.");
          }
        };
      }
      if (caret && menu) {
        caret.onclick = (event) => {
          event.stopPropagation();
          menu.hidden = !menu.hidden;
        };
      }
      card.querySelectorAll("[data-mode]").forEach((btn) => {
        btn.onclick = (event) => {
          event.stopPropagation();
          this.sendMode = btn.dataset.mode;
          if (threadId) this.threadModes[threadId] = this.sendMode;
          if (menu) menu.hidden = true;
          if (sendBtn) sendBtn.textContent = this.sendLabel(thread);
          if (textarea) textarea.placeholder = this.composerPlaceholder(thread);
        };
      });
      const send = () => {
        if (menu) menu.hidden = true;
        const content = textarea?.value.trim();
        if (!content) return;
        this.dispatchSend(threadId, content);
        textarea.value = "";
      };
      if (sendBtn) {
        sendBtn.onclick = (event) => {
          event.stopPropagation();
          send();
        };
      }
      if (textarea) {
        textarea.addEventListener("keydown", (event) => {
          if (event.key === "Enter" && !event.shiftKey) {
            event.preventDefault();
            send();
          }
        });
      }
    }
    effectiveSendMode(thread) {
      if (thread?.id && this.threadModes[thread.id]) return this.threadModes[thread.id];
      const agent = lastConversationAgent(thread);
      if (agent) return agent;
      return this.sendMode || "comment";
    }
    sendLabel(thread) {
      if (thread?.awaitingAgent?.status === "pending") return "Waiting\u2026";
      if (thread?.awaitingAgent?.status === "error") return "Save agent reply";
      const mode = this.effectiveSendMode(thread);
      if (mode === "cursor") return "Ask Cursor";
      if (mode === "claude-code") return "Ask Claude Code";
      return "Comment";
    }
    composerPlaceholder(thread) {
      const awaiting = thread?.awaitingAgent;
      if (awaiting?.status === "pending") {
        return `Waiting for ${agentName(awaiting.agent)}\u2026`;
      }
      if (awaiting?.status === "error") {
        const name = agentName(awaiting.agent);
        return `Paste ${name}\u2019s reply only if the host failed\u2026`;
      }
      const mode = this.effectiveSendMode(thread);
      if (mode === "cursor") return "Reply to Cursor\u2026";
      if (mode === "claude-code") return "Reply to Claude Code\u2026";
      return "Write a comment\u2026";
    }
    dispatchSend(threadId, content) {
      const thread = this.page?.threads.find((t) => t.id === threadId);
      const awaiting = thread?.awaitingAgent;
      if (awaiting?.status === "pending") return;
      const mode = this.effectiveSendMode(thread);
      if (awaiting?.status === "error" && mode !== "comment") {
        const agent2 = awaiting.agent || "cursor";
        this.awaitingAgent = null;
        this.handlers.onAgentReply?.(threadId, content, agent2);
        return;
      }
      if (mode === "comment") {
        this.handlers.onNote?.(threadId, content);
        return;
      }
      const agent = mode === "claude-code" ? "claude-code" : "cursor";
      this.threadModes[threadId] = mode;
      this.sendMode = mode;
      this.awaitingAgent = { threadId, agent };
      this.handlers.onAgent?.(threadId, content, agent);
    }
    layoutCards() {
      if (!this.els?.gutter) return;
      const docHeight = Math.max(
        document.documentElement.scrollHeight,
        document.body?.scrollHeight || 0,
        window.innerHeight
      );
      document.documentElement.style.setProperty("--lp-doc-height", `${docHeight}px`);
      this.host.style.height = `${docHeight}px`;
      const cards = [...this.els.gutter.querySelectorAll(".card")];
      const items = cards.map((el) => {
        const rect = highlightRect(el.dataset.highlight);
        const preferred = rect ? rect.top + window.scrollY : 12;
        return { el, preferred, height: el.offsetHeight || 72 };
      }).sort((a, b) => a.preferred - b.preferred);
      let cursor = 12;
      for (const item of items) {
        const top = Math.max(item.preferred, cursor);
        item.el.style.top = `${top}px`;
        cursor = top + item.height + CARD_GAP;
      }
    }
    openThread(threadId) {
      const thread = this.page?.threads.find((t) => t.id === threadId);
      if (!thread) return;
      this.activeThreadId = threadId;
      this.renderCards();
      const card = this.els.gutter.querySelector(`.card[data-thread="${CSS.escape(threadId)}"]`);
      const textarea = card?.querySelector("textarea");
      if (textarea) {
        requestAnimationFrame(() => textarea.focus());
      }
      if (card) {
        const top = parseFloat(card.style.top || "0");
        const viewTop = window.scrollY;
        const viewBottom = viewTop + window.innerHeight;
        if (top < viewTop + 24 || top > viewBottom - 160) {
          window.scrollTo({ top: Math.max(0, top - 80), behavior: "smooth" });
        }
      }
    }
    closePanel() {
      this.activeThreadId = null;
      this.renderCards();
    }
    threadFor(highlightId) {
      const threads = (this.page?.threads || []).filter((t) => t.highlightId === highlightId);
      if (!threads.length) return null;
      const active = threads.find((t) => t.id === this.activeThreadId);
      if (active) return active;
      return threads.find((t) => !t.parentId) || threads[0];
    }
    markActiveHighlights() {
      const thread = this.page?.threads.find((t) => t.id === this.activeThreadId);
      document.querySelectorAll("mark.lp-hl").forEach((mark) => {
        mark.classList.toggle("is-active", Boolean(thread && mark.dataset.lpId === thread.highlightId));
      });
    }
  };
  function clip(text, n) {
    const s = String(text || "").replace(/\s+/g, " ");
    return s.length <= n ? s : `${s.slice(0, n - 1)}\u2026`;
  }
  function escapeHtml(value) {
    return String(value || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  function labelOf(message) {
    if (message.role === "agent") return `Agent \xB7 ${message.agent || "unknown"}`;
    if (message.role === "system") return "System";
    return "You";
  }
  function lastConversationAgent(thread) {
    const messages = thread?.messages || [];
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i].role === "agent") {
        return messages[i].agent === "claude-code" ? "claude-code" : "cursor";
      }
    }
    return null;
  }
  function nextForkLabel(page2, source) {
    const siblings = (page2?.threads || []).filter(
      (t) => t.highlightId === source.highlightId && (t.parentId === source.id || t.id === source.id)
    );
    return `branch-${siblings.length}`;
  }
  function agentName(agent) {
    return agent === "claude-code" ? "Claude Code" : "Cursor Agent";
  }
  function awaitingCopy(awaiting) {
    if (awaiting?.status === "error") {
      return `${agentName(awaiting.agent)} did not reply. Keep npm run agent-host running so it can call your local agent / claude CLIs.`;
    }
    return `Asking ${agentName(awaiting?.agent)}\u2026`;
  }

  // extension/content/selection.js
  function toolbarAction({ liveHasRange, gestureSelected: gestureSelected2, savedRange: savedRange2 }) {
    if (liveHasRange) return "show";
    if (gestureSelected2 && savedRange2 && !savedRange2.collapsed) return "show";
    return "hide";
  }
  function rangeRect(range) {
    if (!range || range.collapsed) return null;
    try {
      const box = range.getBoundingClientRect();
      if (box.width || box.height) return box;
      const next = [...range.getClientRects()].find((r) => r.width || r.height);
      return next || null;
    } catch {
      return null;
    }
  }

  // extension/shared/progress.js
  function measureScrollProgress(win = window, doc = document) {
    const root = doc.documentElement;
    const body = doc.body;
    const total = Math.max(root?.scrollHeight || 0, body?.scrollHeight || 0, 1);
    const seen = (win.scrollY || root?.scrollTop || 0) + (win.innerHeight || 0);
    return clampPercent(Math.round(seen / total * 100));
  }
  function clampPercent(value) {
    const n = Number(value);
    if (!Number.isFinite(n)) return 0;
    return Math.min(100, Math.max(0, Math.round(n)));
  }

  // extension/shared/url.js
  var TRACKING_PARAMS = /* @__PURE__ */ new Set([
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_term",
    "utm_content",
    "utm_id",
    "fbclid",
    "gclid",
    "gclsrc",
    "dclid",
    "msclkid",
    "mc_cid",
    "mc_eid",
    "igshid",
    "si",
    "ref",
    "ref_src",
    "ref_url",
    "spm",
    "vero_id",
    "yclid"
  ]);
  function canonicalizeUrl(raw) {
    if (!raw) return "";
    let url;
    try {
      url = new URL(raw);
    } catch {
      return String(raw).split("#")[0];
    }
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      return url.toString();
    }
    url.hash = "";
    url.hostname = url.hostname.replace(/^www\./i, "").toLowerCase();
    const kept = [];
    for (const [key, value] of url.searchParams.entries()) {
      if (TRACKING_PARAMS.has(key.toLowerCase())) continue;
      kept.push([key, value]);
    }
    kept.sort(([a], [b]) => a.localeCompare(b));
    url.search = "";
    for (const [key, value] of kept) url.searchParams.append(key, value);
    let path = url.pathname.replace(/\/{2,}/g, "/");
    if (path.length > 1 && path.endsWith("/")) path = path.slice(0, -1);
    url.pathname = path || "/";
    return url.toString();
  }

  // extension/shared/tags.js
  function normalizeTag(value) {
    const slug = String(value || "").toLowerCase().trim().replace(/[#]+/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    if (!slug || slug.length > 48) return "";
    return slug;
  }
  function parseTagInput(value) {
    return mergeTags(
      String(value || "").split(/[,;\n]+/).map((part) => part.trim().replace(/^#/, ""))
    );
  }
  function mergeTags(...lists) {
    const seen = /* @__PURE__ */ new Set();
    const out = [];
    for (const list of lists) {
      for (const raw of list || []) {
        const tag = normalizeTag(raw);
        if (!tag || seen.has(tag)) continue;
        seen.add(tag);
        out.push(tag);
      }
    }
    return out;
  }

  // extension/import/rss.js
  var RSS_TYPES = /rss|atom|\+xml/i;
  function detectFeeds(doc, pageUrl) {
    if (!doc) return [];
    if (looksLikeFeedDocument(doc, pageUrl)) {
      return [
        {
          url: canonicalizeUrl(pageUrl),
          title: textOf(doc.querySelector("title, channel > title")) || doc.title || "RSS"
        }
      ];
    }
    const out = [];
    const seen = /* @__PURE__ */ new Set();
    const nodes = doc.querySelectorAll?.('link[rel~="alternate"], a[rel~="alternate"]') || [];
    for (const node of nodes) {
      const type = String(node.getAttribute?.("type") || "");
      const href = node.getAttribute?.("href") || node.href;
      if (!href) continue;
      if (type && !RSS_TYPES.test(type)) continue;
      if (!type && !looksLikeFeedHref(href)) continue;
      let url = "";
      try {
        url = canonicalizeUrl(new URL(href, pageUrl).href);
      } catch {
        continue;
      }
      if (seen.has(url)) continue;
      seen.add(url);
      out.push({
        url,
        title: node.getAttribute?.("title") || doc.title || "RSS"
      });
    }
    return out;
  }
  function looksLikeFeedHref(href) {
    return /(\.rss|\.atom|\.xml|\/feed\/?|\/rss\/?|\/atom\/?)/i.test(String(href || ""));
  }
  function looksLikeFeedDocument(doc, pageUrl) {
    const root = doc.documentElement?.localName || doc.documentElement?.tagName || "";
    if (/^(rss|feed|rdf)$/i.test(root)) return true;
    return looksLikeFeedHref(pageUrl);
  }
  function textOf(node) {
    return node?.textContent?.trim() || "";
  }

  // extension/shared/flags.js
  var FLAG_DEFAULTS = {
    forYouFeed: true,
    readingList: true,
    bookmarks: true,
    saves: true,
    review: true,
    rss: true,
    localTweets: false,
    importSaves: true,
    dashboardLayout: "feed"
  };
  var EXPERIMENTS = {
    "dashboard-density": {
      id: "dashboard-density",
      name: "Dashboard density",
      blurb: "How much the home surface should show at once.",
      variants: {
        A: {
          label: "A \xB7 feed",
          hint: "For you as a timeline. Local observations stay off unless you turn them on.",
          flags: {
            forYouFeed: true,
            dashboardLayout: "feed",
            localTweets: false
          }
        },
        B: {
          label: "B \xB7 lists",
          hint: "Skip the timeline. Start in lists so sources stay in their own rooms.",
          flags: {
            forYouFeed: false,
            dashboardLayout: "lists",
            localTweets: false
          }
        },
        C: {
          label: "C \xB7 compact",
          hint: "Top nav, dense rows, detail docked beside the list. Same rooms, less chrome.",
          flags: {
            forYouFeed: true,
            dashboardLayout: "compact",
            localTweets: false
          }
        }
      }
    }
  };
  var DEFAULT_EXPERIMENT = {
    id: "dashboard-density",
    variant: "A"
  };
  function resolveFlags(settings2 = {}) {
    const experiment = normalizeExperiment(settings2.experiment);
    const variantFlags = EXPERIMENTS[experiment.id]?.variants?.[experiment.variant]?.flags || {};
    const legacy = {};
    if (typeof settings2.localTweetsEnabled === "boolean") {
      legacy.localTweets = settings2.localTweetsEnabled;
    }
    if (typeof settings2.importSavesEnabled === "boolean") {
      legacy.importSaves = settings2.importSavesEnabled;
    }
    const flags = {
      ...FLAG_DEFAULTS,
      ...variantFlags,
      ...legacy,
      ...settings2.flags || {}
    };
    if (!["feed", "lists", "compact"].includes(flags.dashboardLayout)) flags.dashboardLayout = "feed";
    return { flags, experiment };
  }
  function normalizeExperiment(value) {
    const id = value?.id && EXPERIMENTS[value.id] ? value.id : DEFAULT_EXPERIMENT.id;
    const variant = EXPERIMENTS[id].variants[value?.variant] ? value.variant : "A";
    return { id, variant };
  }

  // extension/content/content.js
  if (globalThis.__LP_CONTENT_STARTED) {
    throw new Error("LivePage content already started");
  }
  globalThis.__LP_CONTENT_STARTED = true;
  var overlay = new Overlay();
  var page = null;
  var settings = { defaultColor: "lemon", lockInfiniteScroll: true, allowInfiniteSnapshot: true };
  var infinite = { infinite: false, reason: null };
  var snapshotMode = false;
  var savedRange = null;
  var savedRect = null;
  var gestureSelected = false;
  overlay.handlers = {
    onSnapshot: () => snapshot(),
    onOpenHighlight: (id) => openOrCreateThread(id),
    onNote: (threadId, content) => mutate("ADD_MESSAGE", { pageId: page.id, threadId, message: { role: "user", content } }),
    onAgent: (threadId, ask, agent) => sendToAgent(threadId, ask, agent),
    onAgentReply: (threadId, content, agent) => mutate("ADD_MESSAGE", {
      pageId: page.id,
      threadId,
      message: { role: "agent", agent, content }
    }),
    onFork: (threadId, messageId, branchLabel) => mutate("FORK_THREAD", { pageId: page.id, threadId, messageId, branchLabel }).then((data) => {
      overlay.openThread(data.thread.id);
    }),
    onDeleteMessage: (threadId, messageId) => mutate("DELETE_MESSAGE", { pageId: page.id, threadId, messageId }),
    onRecolorHighlight: (highlightId, color) => recolorHighlight(highlightId, color),
    onMoveHighlight: (highlightId) => moveHighlight(highlightId),
    onDeleteHighlight: (highlightId) => deleteHighlight(highlightId)
  };
  onBroadcast((message) => {
    if (message.kind === "CONTEXT_ACTION") handleContext(message.action);
    if (message.kind === "TOAST" && message.text) overlay.toast(message.text);
  });
  boot().catch((error) => console.warn("LivePage failed to start", error));
  async function boot() {
    infinite = evaluateInfiniteScroll(location.href, document);
    watchSelection();
    watchMarks();
    try {
      settings = await call("GET_SETTINGS") || settings;
    } catch (error) {
      console.warn("LivePage settings unavailable", error);
    }
    const { flags } = resolveFlags(settings);
    try {
      await overlay.ready;
    } catch (error) {
      console.warn("LivePage overlay failed", error);
    }
    maybeToolbar();
    let parsed = { blocks: [] };
    try {
      parsed = parseDocument(document, location.href);
    } catch (error) {
      console.warn("LivePage parse failed", error);
    }
    if (!infinite.infinite) infinite = evaluateInfiniteScroll(location.href, document);
    try {
      page = await call("VISIT_PAGE", {
        url: location.href,
        title: document.title,
        parsed,
        infiniteScroll: infinite.infinite
      });
      if (page.snapshot) snapshotMode = true;
      restoreHighlights(document.body, page.highlights);
      overlay.setPage(page);
      applyLock();
      watchInfinite();
      watchScroll();
    } catch (error) {
      console.warn("LivePage visit failed", error);
    }
    if (flags.rss) offerRssIfAny();
  }
  function watchInfinite() {
    if (infinite.infinite) return;
    const detector = createInfiniteScrollDetector({
      initial: false,
      minGrowths: 2,
      threshold: 0.35
    });
    detector.onFlag(() => {
      infinite = { infinite: true, reason: "This page grew while you were reading." };
      call("PATCH_PAGE", { id: page.id, patch: { infiniteScroll: true } });
      applyLock();
    });
    detector.start();
  }
  function applyLock() {
    const shouldLock = Boolean(
      settings.lockInfiniteScroll && infinite.infinite && !snapshotMode
    );
    overlay.setLock({
      locked: shouldLock,
      reason: infinite.reason,
      snapshotTexts: snapshotMode ? (page.parsed?.blocks || []).map((b) => b.text) : null
    });
  }
  async function snapshot() {
    const parsed = parseDocument(document, location.href);
    page = await call("PATCH_PAGE", { id: page.id, patch: { parsed, infiniteScroll: true } });
    page = await call("SNAPSHOT_PAGE", { pageId: page.id });
    snapshotMode = true;
    overlay.setPage(page);
    applyLock();
    overlay.toast("Snapshot taken. You can annotate this view.");
  }
  function watchScroll() {
    let lastSent = 0;
    const report = () => {
      if (!page?.id) return;
      const percent = measureScrollProgress();
      call("REPORT_PROGRESS", {
        pageId: page.id,
        percent,
        scrollY: window.scrollY
      }).then((next) => {
        if (next) page = next;
      });
    };
    window.addEventListener(
      "scroll",
      () => {
        const now = Date.now();
        if (now - lastSent < 800) return;
        lastSent = now;
        report();
      },
      { passive: true }
    );
    report();
  }
  function eventFromOverlay(event) {
    return overlay.ownsEvent?.(event);
  }
  function watchSelection() {
    overlay.attachHosts?.();
    const finishGesture = () => {
      requestAnimationFrame(() => maybeToolbar());
      setTimeout(() => maybeToolbar(), 40);
    };
    document.addEventListener(
      "pointerdown",
      (event) => {
        if (eventFromOverlay(event)) return;
        gestureSelected = false;
        overlay.hideToolbar();
      },
      true
    );
    document.addEventListener(
      "pointerup",
      (event) => {
        if (eventFromOverlay(event)) return;
        finishGesture();
      },
      true
    );
    document.addEventListener("keyup", (event) => {
      if (event.key === "Escape") {
        savedRange = null;
        savedRect = null;
        gestureSelected = false;
        overlay.hideToolbar();
        return;
      }
      if (event.shiftKey || event.key.startsWith("Arrow")) finishGesture();
    });
    document.addEventListener("selectionchange", () => {
      const selection = window.getSelection();
      if (!selection || selection.isCollapsed || !selection.rangeCount) return;
      gestureSelected = true;
      captureSelection(selection);
    });
  }
  function captureSelection(selection = window.getSelection()) {
    if (!selection || selection.isCollapsed || !selection.rangeCount) return false;
    if (selection.anchorNode && overlay.host?.contains(selection.anchorNode)) return false;
    if (selection.anchorNode && overlay.floatHost?.contains(selection.anchorNode)) return false;
    savedRange = selection.getRangeAt(0).cloneRange();
    savedRect = rangeRect(savedRange);
    return true;
  }
  function maybeToolbar() {
    overlay.attachHosts?.();
    if (!overlay.els?.toolbar) {
      overlay.ready.then(() => maybeToolbar()).catch(() => {
      });
      return;
    }
    const selection = window.getSelection();
    const liveHasRange = Boolean(selection && !selection.isCollapsed && selection.rangeCount);
    if (liveHasRange) captureSelection(selection);
    if (toolbarAction({ liveHasRange, gestureSelected, savedRange }) === "hide") {
      overlay.hideToolbar();
      return;
    }
    const rect = rangeRect(savedRange) || savedRect;
    if (!rect) return;
    savedRect = rect;
    const locked = settings.lockInfiniteScroll && infinite.infinite && !snapshotMode;
    if (locked) {
      overlay.showToolbar(rect, {
        onSnapshot: () => overlay.handlers.onSnapshot?.()
      });
      return;
    }
    if (snapshotMode && liveHasRange && !selectionIsSafe(selection, (page?.parsed?.blocks || []).map((b) => b.text))) {
      overlay.toast("That span arrived after the snapshot. Ignore or snapshot again.");
      overlay.hideToolbar();
      return;
    }
    overlay.showToolbar(rect, {
      onHighlight: (color) => createFromSelection({ color }),
      onComment: () => createFromSelection({ color: settings.defaultColor, comment: true })
    });
  }
  async function ensurePage() {
    if (page?.id) return page;
    const parsed = parseDocument(document, location.href);
    page = await call("VISIT_PAGE", {
      url: location.href,
      title: document.title,
      parsed,
      infiniteScroll: infinite.infinite
    });
    overlay.setPage(page);
    return page;
  }
  async function createFromSelection({ color, comment = false }) {
    captureSelection();
    const range = savedRange;
    if (!range || range.collapsed) return;
    const quote = quoteFromRange(range, document.body);
    if (!quote) {
      overlay.toast("Could not read that selection. Try a longer span of text.");
      return;
    }
    try {
      await overlay.ready;
      await ensurePage();
      const result = await call("ADD_HIGHLIGHT", {
        pageId: page.id,
        highlight: { color, text: quote.exact, prefix: quote.prefix, suffix: quote.suffix }
      });
      page = result.page;
      applyRangeHighlight(range, result.highlight);
      window.getSelection()?.removeAllRanges();
      savedRange = null;
      overlay.setPage(page);
      if (comment && result.thread) overlay.openThread(result.thread.id);
    } catch (error) {
      overlay.toast("Could not save that highlight. Reload the tab and try again.");
      console.warn("LivePage highlight", error);
    }
  }
  async function recolorHighlight(highlightId, color) {
    try {
      const result = await call("PATCH_HIGHLIGHT", {
        pageId: page.id,
        highlightId,
        patch: { color }
      });
      page = result.page;
      recolorMarks(highlightId, color);
      overlay.setPage(page);
    } catch (error) {
      overlay.toast("Could not change that color.");
      console.warn("LivePage recolor", error);
    }
  }
  async function moveHighlight(highlightId) {
    captureSelection();
    const range = savedRange;
    if (!range || range.collapsed) {
      overlay.toast("Select the new span on the page, then click Replace span.");
      return;
    }
    const quote = quoteFromRange(range, document.body);
    if (!quote) {
      overlay.toast("Could not read that selection. Try a longer span of text.");
      return;
    }
    try {
      const result = await call("PATCH_HIGHLIGHT", {
        pageId: page.id,
        highlightId,
        patch: { text: quote.exact, prefix: quote.prefix, suffix: quote.suffix }
      });
      page = result.page;
      applyRangeHighlight(range, result.highlight);
      window.getSelection()?.removeAllRanges();
      savedRange = null;
      overlay.hideToolbar();
      overlay.setPage(page);
      overlay.toast("Highlight moved to that span.");
    } catch (error) {
      overlay.toast("Could not move that highlight.");
      console.warn("LivePage move highlight", error);
    }
  }
  async function deleteHighlight(highlightId) {
    try {
      unwrapHighlight(document, highlightId);
      if (overlay.activeThreadId) {
        const thread = page?.threads?.find((t) => t.id === overlay.activeThreadId);
        if (!thread || thread.highlightId === highlightId) overlay.closePanel();
      }
      const result = await call("REMOVE_HIGHLIGHT", { pageId: page.id, highlightId });
      page = result.page || result;
      overlay.setPage(page);
      overlay.toast("Highlight removed.");
    } catch (error) {
      overlay.toast("Could not delete that highlight.");
      console.warn("LivePage delete highlight", error);
    }
  }
  function watchMarks() {
    document.addEventListener("click", (event) => {
      const mark = event.target.closest?.("mark.lp-hl");
      if (!mark) return;
      openOrCreateThread(mark.dataset.lpId);
    });
  }
  function openOrCreateThread(highlightId) {
    if (!page?.threads) return;
    const existing = page.threads.find((t) => t.highlightId === highlightId && !t.parentId) || page.threads.find((t) => t.highlightId === highlightId);
    if (existing) overlay.openThread(existing.id);
  }
  async function sendToAgent(threadId, ask, agent) {
    try {
      overlay.toast("Asking the agent\u2026");
      const result = await call("ASK_AGENT", {
        pageId: page.id,
        threadId,
        ask,
        agent
      });
      page = result.page;
      overlay.setPage(page);
      overlay.openThread(result.thread.id);
      overlay.toast("Reply landed in the thread.");
    } catch (error) {
      overlay.toast(String(error.message || error));
      console.warn("LivePage agent", error);
      try {
        page = await call("GET_PAGE", { id: page.id });
        overlay.setPage(page);
      } catch {
      }
    }
  }
  async function mutate(type, payload) {
    const result = await call(type, payload);
    page = result.page || result;
    overlay.setPage(page);
    if (result.thread) overlay.openThread(result.thread.id);
    return result;
  }
  function handleContext(action) {
    if (settings.lockInfiniteScroll && infinite.infinite && !snapshotMode) {
      overlay.toast("Snapshot this page before highlighting. Infinite pages cannot keep stable anchors.");
      return;
    }
    captureSelection();
    if (action === "comment") createFromSelection({ color: settings.defaultColor, comment: true });
    else createFromSelection({ color: settings.defaultColor || COLOR_IDS[0] });
  }
  if (typeof chrome !== "undefined" && chrome.runtime?.onMessage) {
    chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
      if (message?.kind !== "ADD_RSS_FEED") return;
      offerRssIfAny({ force: true }).then(() => sendResponse({ ok: true })).catch(() => sendResponse({ ok: false }));
      return true;
    });
  }
  async function offerRssIfAny({ force = false } = {}) {
    const feeds = detectFeeds(document, location.href);
    if (!feeds.length) {
      if (force && overlay.els) overlay.toast("No RSS/Atom feed found on this page.");
      return;
    }
    if (!overlay.els) {
      if (force) {
        await call("ADD_RSS_FEED", { url: feeds[0].url, title: feeds[0].title });
      }
      return;
    }
    const { flags } = resolveFlags(settings);
    if (!flags.rss && !force) return;
    const known = new Set((settings.rssFeeds || []).map((feed2) => feed2.url));
    const feed = feeds.find((item) => !known.has(item.url)) || (force ? feeds[0] : null);
    if (!feed) return;
    overlay.offerFeed(feed, {
      onAdd: async (rawTags) => {
        const result = await call("ADD_RSS_FEED", {
          url: feed.url,
          title: feed.title,
          tags: parseTagInput(rawTags)
        });
        settings = result?.settings || await call("GET_SETTINGS") || settings;
        overlay.offerFeed(null);
        overlay.toast(
          result?.itemCount ? `Feed added. Pulled ${result.itemCount} item${result.itemCount === 1 ? "" : "s"}.` : "Feed added. Items will show under RSS when the feed has entries."
        );
      },
      onDismiss: () => overlay.offerFeed(null)
    });
  }
})();
